import unittest

from codequality.generated_code import is_generated

NORMAL_SOURCE = '''"""A perfectly ordinary hand-written module."""


def add(a, b):
    """Add two numbers."""
    return a + b
'''


class TestContentMarkers(unittest.TestCase):
    def _source_with_header(self, header_line):
        return f"{header_line}\n\ndef f():\n    return 1\n"

    def test_do_not_edit(self):
        src = self._source_with_header("# DO NOT EDIT this file, it is managed elsewhere.")
        self.assertTrue(is_generated("thing.py", src))

    def test_generated_annotation(self):
        src = self._source_with_header("// @generated by some-tool")
        self.assertTrue(is_generated("thing.js", src))

    def test_code_generated_by(self):
        src = self._source_with_header("// Code generated by protoc-gen-go. DO NOT EDIT.")
        self.assertTrue(is_generated("thing.go", src))

    def test_automatically_generated(self):
        src = self._source_with_header("# This file was automatically generated by openapi-generator.")
        self.assertTrue(is_generated("client.py", src))

    def test_autogenerated_one_word(self):
        src = self._source_with_header("# autogenerated -- do not modify by hand")
        self.assertTrue(is_generated("client.py", src))

    def test_auto_generated_hyphenated(self):
        src = self._source_with_header("# auto-generated file")
        self.assertTrue(is_generated("client.py", src))

    def test_markers_are_case_insensitive(self):
        src = self._source_with_header("# CODE GENERATED BY SOME TOOL. DO NOT EDIT.")
        self.assertTrue(is_generated("thing.py", src))

    def test_marker_word_inside_prose_line_is_not_flagged(self):
        """A docstring paragraph that *discusses* generated-code markers as
        an example (quoting phrases like "DO NOT EDIT" or "code generated
        by" inline in a sentence) shouldn't itself be treated as a
        generated file -- only an actual standalone comment line counts.
        Regression test for a real false positive found scanning this
        project's own source (see generated_code.py's module docstring)."""
        src = (
            '"""Explains how detection works.\n\n'
            'Generation tools emit a line like "Code generated by protoc. '
            'DO NOT EDIT." near the top of the file, which this module looks for.\n'
            '"""\n\n'
            "def f():\n    return 1\n"
        )
        self.assertFalse(is_generated("explainer.py", src))

    def test_marker_deep_in_file_is_not_flagged(self):
        """A marker-looking string far past the header shouldn't count --
        this is a normal file that happens to discuss code generation (e.g.
        a docstring or comment in a linter/codegen tool's own source), not
        an actually-generated file."""
        padding = "\n".join(f"x{i} = {i}" for i in range(40))
        src = f'"""A normal module."""\n\n{padding}\n\n# Reminder: do not edit generated files by hand.\n'
        self.assertFalse(is_generated("normal_module.py", src))


class TestFilenameFallback(unittest.TestCase):
    def test_pb2_suffix(self):
        self.assertTrue(is_generated("foo_pb2.py", NORMAL_SOURCE))

    def test_pb2_grpc_suffix(self):
        self.assertTrue(is_generated("foo_pb2_grpc.py", NORMAL_SOURCE))

    def test_dot_generated_dot(self):
        self.assertTrue(is_generated("api.generated.ts", NORMAL_SOURCE))

    def test_generated_directory(self):
        self.assertTrue(is_generated("src/generated/client.py", NORMAL_SOURCE))

    def test_dunder_generated_directory(self):
        self.assertTrue(is_generated("src/__generated__/client.py", NORMAL_SOURCE))

    def test_alembic_style_migration(self):
        self.assertTrue(is_generated("migrations/versions/1a2b3c4d5e6f_add_users_table.py", NORMAL_SOURCE))

    def test_django_style_migration(self):
        self.assertTrue(is_generated("app/migrations/0001_initial.py", NORMAL_SOURCE))

    def test_migrations_dir_without_revision_filename_not_flagged(self):
        """A plain __init__.py or env.py living in a migrations directory
        isn't itself a generated revision file, so the filename fallback
        shouldn't trigger just because of the directory name."""
        self.assertFalse(is_generated("migrations/versions/__init__.py", NORMAL_SOURCE))

    def test_content_marker_takes_precedence_but_fallback_still_works_alone(self):
        # Sanity: filename fallback alone (no content marker) still works.
        self.assertTrue(is_generated("foo_pb2.py", NORMAL_SOURCE))


class TestNormalFiles(unittest.TestCase):
    def test_ordinary_hand_written_file_not_flagged(self):
        self.assertFalse(is_generated("codequality/scanner.py", NORMAL_SOURCE))

    def test_ordinary_file_named_similarly_but_not_matching(self):
        self.assertFalse(is_generated("generated_report.py", NORMAL_SOURCE))

    def test_none_source_not_flagged(self):
        self.assertFalse(is_generated("foo_pb2.py", None))


if __name__ == "__main__":
    unittest.main()
