"""scan_repo's file-discovery/analysis pipeline, focused on the
auto-generated-file exclusion (see codequality/generated_code.py). scan_repo
needs no git repo -- only discover_files + analyze_file -- so a plain temp
directory is enough here.
"""

import os
import shutil
import tempfile
import unittest

from codequality.config import Config
from codequality.scanner import scan_repo

NORMAL_SOURCE = '''"""A perfectly ordinary hand-written module."""


def add(a, b):
    """Add two numbers."""
    return a + b
'''

GENERATED_SOURCE = '''# Code generated by protoc. DO NOT EDIT.
"""Generated protobuf module."""


def internal_only():
    return 1
'''


class TestGeneratedFileExclusion(unittest.TestCase):
    def setUp(self):
        self.root = tempfile.mkdtemp(prefix="cq-scanner-test-")
        with open(os.path.join(self.root, "normal.py"), "w") as f:
            f.write(NORMAL_SOURCE)
        with open(os.path.join(self.root, "thing_pb2.py"), "w") as f:
            f.write(GENERATED_SOURCE)

    def tearDown(self):
        shutil.rmtree(self.root, ignore_errors=True)

    def test_generated_file_excluded_by_default(self):
        config = Config({})
        metrics = scan_repo(self.root, config)
        paths = {fm.path for fm in metrics}
        self.assertIn("normal.py", paths)
        self.assertNotIn("thing_pb2.py", paths)

    def test_generated_file_included_when_opted_in(self):
        config = Config({"include_generated": True})
        metrics = scan_repo(self.root, config)
        paths = {fm.path for fm in metrics}
        self.assertIn("normal.py", paths)
        self.assertIn("thing_pb2.py", paths)


if __name__ == "__main__":
    unittest.main()


MESSY_SOURCE = '''def messy(a, b, c, d, e, f):
    if a:
        if b:
            if c:
                if d:
                    x = eval("1+1")
                    return x
    s = ""
    for i in range(100):
        s += str(i)
    return s
'''


class TestParallelScanDeterminism(unittest.TestCase):
    """scan_repo(jobs=N) must produce identical results for any N."""

    def setUp(self):
        self.root = tempfile.mkdtemp(prefix="cq-parallel-test-")
        for i in range(6):
            with open(os.path.join(self.root, f"mod_{i}.py"), "w") as f:
                f.write(NORMAL_SOURCE if i % 2 else MESSY_SOURCE)

    def tearDown(self):
        shutil.rmtree(self.root, ignore_errors=True)

    def _snapshot(self, metrics):
        return [
            (fm.path, fm.loc, len(fm.functions), [i.to_dict() for i in fm.issues])
            for fm in metrics
        ]

    def test_parallel_matches_sequential(self):
        config = Config({})
        sequential = self._snapshot(scan_repo(self.root, config, jobs=1))
        parallel = self._snapshot(scan_repo(self.root, config, jobs=2))
        self.assertEqual(sequential, parallel)

    def test_jobs_zero_means_auto(self):
        config = Config({})
        sequential = self._snapshot(scan_repo(self.root, config, jobs=1))
        auto = self._snapshot(scan_repo(self.root, config, jobs=0))
        self.assertEqual(sequential, auto)
