"""scan_repo's file-discovery/analysis pipeline, focused on the
auto-generated-file exclusion (see codequality/generated_code.py). scan_repo
needs no git repo -- only discover_files + analyze_file -- so a plain temp
directory is enough here.
"""

import os
import shutil
import tempfile
import unittest

from codequality.config import Config
from codequality.scanner import scan_repo

NORMAL_SOURCE = '''"""A perfectly ordinary hand-written module."""


def add(a, b):
    """Add two numbers."""
    return a + b
'''

GENERATED_SOURCE = '''# Code generated by protoc. DO NOT EDIT.
"""Generated protobuf module."""


def internal_only():
    return 1
'''


class TestGeneratedFileExclusion(unittest.TestCase):
    def setUp(self):
        self.root = tempfile.mkdtemp(prefix="cq-scanner-test-")
        with open(os.path.join(self.root, "normal.py"), "w") as f:
            f.write(NORMAL_SOURCE)
        with open(os.path.join(self.root, "thing_pb2.py"), "w") as f:
            f.write(GENERATED_SOURCE)

    def tearDown(self):
        shutil.rmtree(self.root, ignore_errors=True)

    def test_generated_file_excluded_by_default(self):
        config = Config({})
        metrics = scan_repo(self.root, config)
        paths = {fm.path for fm in metrics}
        self.assertIn("normal.py", paths)
        self.assertNotIn("thing_pb2.py", paths)

    def test_generated_file_included_when_opted_in(self):
        config = Config({"include_generated": True})
        metrics = scan_repo(self.root, config)
        paths = {fm.path for fm in metrics}
        self.assertIn("normal.py", paths)
        self.assertIn("thing_pb2.py", paths)


if __name__ == "__main__":
    unittest.main()
