"""Detect files that are machine-generated so `scan`/`diff` can exclude them
from scoring by default.

Complexity, duplication, documentation, and style checks all assume a human
is going to read (and could improve) the file being scored. That assumption
breaks down for generated code -- protobuf `_pb2.py` output, OpenAPI/Swagger
client stubs, Alembic/Django migrations, ORM-generated models, and similar --
nobody hand-edits these, so a missing docstring or a long function in a
generated client is noise, not a real quality signal, and a single large
generated file can meaningfully skew a repo's score if counted like
hand-written code.

Detection is content-first: most generation tools (protoc, openapi-generator,
swagger-codegen, GraphQL codegen, ...) emit a recognizable marker as its own
comment line near the top of the file, which is checked case-insensitively
against roughly the first 20 lines. This is the primary signal because it's
tool-agnostic and doesn't depend on any naming convention.

The marker check only looks at lines that are themselves a comment (start
with `#`, `//`, `/*`, `*`, `<!--`, or `--`, the common comment leaders across
supported languages) -- never a full-line substring search over arbitrary
prose. That's deliberate: a docstring or README paragraph that merely
*discusses* code generation (this module's own docstring above does, and so
does `codequality/baseline.py`'s, which calls a baseline "a bulk
auto-generated suppression list") would otherwise trip the same substring
match a real generator header does. Restricting the check to comment lines
catches every mainstream convention (protoc's `# Generated by the protocol
buffer compiler.  DO NOT EDIT!`, GraphQL codegen's `// @generated`, ...)
while leaving hand-written explanatory prose alone.

Filename/path patterns are a fallback, used *only* when no content marker
matched, and deliberately scoped to a short list of well-established,
unambiguous conventions (protobuf's `_pb2.py`/`_pb2_grpc.py` suffix, Alembic/
Django-style migration filenames, `*.generated.*`, and files under a
directory literally named `generated`/`__generated__`) rather than any broad
guess. False negatives here (missing a generated file) just mean it gets
scored like normal code -- mildly annoying. False positives (silently
excluding real hand-written code from scoring) are worse: they hide genuine
quality issues from the report. `is_generated` is written to fail closed
(return `False`) whenever a case is ambiguous.

Design choice -- exclusion, not tagging: `scanner.py` drops a file detected
as generated from the returned metrics list entirely, the same way
`config.exclude` glob patterns already work, rather than tagging
`FileMetrics.is_generated` and teaching every scorer function to skip
tagged files. This repo's existing convention for "don't score this" is
exclusion (see `config.exclude`, `DEFAULT_IGNORE_DIRS`), and file counts in
the summary are meant to reflect what was actually scored -- there's no
existing precedent here for a file that's discovered but not scored. The
`--include-generated` flag (see `cli.py`) opts back in by skipping the
exclusion, not by threading a flag through `scorer.py`.
"""

import os
import re

CONTENT_MARKERS = (
    "do not edit",
    "@generated",
    "code generated by",
    "this file was automatically generated",
    "autogenerated",
    "auto-generated",
)

# How many leading lines of the file count as "near the top" for the
# content-marker check. Generation tool headers always land in the first
# handful of lines; scanning the whole file would risk matching a
# hand-written comment/string deep in an otherwise ordinary file that merely
# *discusses* code generation.
_HEADER_LINES = 20

# Comment leaders across every language this tool touches (Python/shell `#`,
# C-family `//` and `/* */`, HTML/XML `<!--`, SQL `--`). A marker only counts
# when the line it's on starts with one of these, once leading whitespace is
# stripped -- see the module docstring for why.
_COMMENT_PREFIXES = ("#", "//", "/*", "*", "<!--", "--")

# Alembic revision ids are a long hex string; Django migrations are a
# zero-padded numeric prefix (0001_initial.py). Both are followed by an
# underscore and a descriptive slug.
_MIGRATION_NAME_RE = re.compile(r"^([0-9a-f]{8,16}|\d{3,4})_\w*\.py$", re.IGNORECASE)


def _comment_text(line):
    """Strip a recognized comment leader from `line` and return the rest,
    or `None` if `line` isn't a comment line at all (plain code, blank line,
    or prose inside a docstring/string literal)."""
    stripped = line.strip()
    for prefix in _COMMENT_PREFIXES:
        if stripped.startswith(prefix):
            return stripped[len(prefix):]
    return None


def _has_content_marker(source):
    for line in source.splitlines()[:_HEADER_LINES]:
        comment = _comment_text(line)
        if comment is None:
            continue
        comment = comment.lower()
        if any(marker in comment for marker in CONTENT_MARKERS):
            return True
    return False


def _matches_filename_pattern(path):
    norm = path.replace(os.sep, "/").replace("\\", "/")
    parts = [p for p in norm.split("/") if p]
    basename = parts[-1] if parts else norm

    if basename.endswith("_pb2.py") or basename.endswith("_pb2_grpc.py"):
        return True
    if ".generated." in basename:
        return True
    if "generated" in parts[:-1] or "__generated__" in parts[:-1]:
        return True
    if "migrations" in parts[:-1] and _MIGRATION_NAME_RE.match(basename):
        return True
    return False


def is_generated(path, source):
    """True if `path` (with contents `source`) looks machine-generated.

    Checks the content markers first (the reliable, tool-agnostic signal);
    only falls back to filename/path conventions when no content marker was
    found. Defaults to `False` -- an ordinary hand-written file is never
    flagged just because it happens to sit near a suspicious-sounding path.
    """
    if source is None:
        return False
    if _has_content_marker(source):
        return True
    return _matches_filename_pattern(path)
